version: '3.7'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_NAME?Variable not set}-backend-http.rule=PathPrefix(`/api`)
      - traefik.http.services.${PROJECT_NAME?Variable not set}-backend.loadbalancer.server.port=8000
  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_NAME?Variable not set}-frontend-http.rule=PathPrefix(`/`)
      - traefik.http.services.${PROJECT_NAME?Variable not set}-frontend.loadbalancer.server.port=3000
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: yarn start
    volumes:
    - ./frontend/:/app/frontend/

  traefik:
    image: traefik:v2.2
    command:
      - "--api"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    labels:
      # below for HTTPS
      - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-http.rule=Host(`${DOMAIN?Variable not set}`) || Host(`www.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-http.entrypoints=http
      # traefik-https the actual router using HTTPS
      - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.rule=Host(`${DOMAIN?Variable not set}`) || Host(`www.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.tls=true
      # Use the "le" (Let's Encrypt) resolver created below
      - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.tls.certresolver=le
      # Define the port inside of the Docker service to use
      - traefik.http.services.${STACK_NAME?Variable not set}-proxy.loadbalancer.server.port=80
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - backend


