version: '3.7'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_NAME?Variable not set}-backend-http.rule=PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)
      - traefik.http.services.${PROJECT_NAME?Variable not set}-backend.loadbalancer.server.port=8000
  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_NAME?Variable not set}-frontend-http.rule=PathPrefix(`/`)
      - traefik.http.services.${PROJECT_NAME?Variable not set}-frontend.loadbalancer.server.port=3000
    ports:
      - "3000:3000"
    stdin_open: true
    env_file:
      - .env

  traefik:
    image: traefik:v2.2
    command:
      - "--api"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - backend


